### Ping
GET http://localhost:8001/ping?message=hello

### Ping2
GET http://localhost:8001/ping2

### Release Notes
GET http://localhost:8001/releasenotes

### Metrics
GET http://localhost:9091/metrics

### Health
GET http://localhost:8001/health


### Config
GET http://localhost:8001/config
X-API-Key: 1234

### Scheduled Jobs
GET http://localhost:8001/scheduledjobs
X-API-Key: 1234

### Running Jobs
GET http://localhost:8001/runningjobs
X-API-Key: 1234